# Generated by Django 5.0.2 on 2024-03-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('origin', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(choices=[('Fruit', 'Fruit'), ('Grains', 'Grains'), ('Vegetables', 'Vegetables'), ('Legumes', 'Legumes'), ('Oilseeds', 'Oilseeds'), ('Roots and Tubers', 'Roots and Tubers'), ('Nuts', 'Nuts'), ('Tropical Crops', 'Tropical Crops'), ('Indistrial crops', 'Indusctrial Crop')], max_length=100, null=True)),
                ('packaging', models.CharField(max_length=100, null=True)),
                ('harvest_date', models.DateField(null=True)),
                ('cost_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Shelf_life', models.CharField(max_length=100, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Product',
            },
        ),
    ]
