# Generated by Django 5.0.2 on 2024-03-22 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproduct', '0002_make_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='make_order',
            options={'verbose_name_plural': 'Make Order'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Products'},
        ),
    ]
