# Generated by Django 5.0.3 on 2024-03-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproduct', '0005_remove_product_image_sell'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='category',
            field=models.CharField(blank=True, choices=[('Fruit', 'Fruit'), ('Grains', 'Grains'), ('Vegetables', 'Vegetables'), ('Legumes', 'Legumes'), ('Oilseeds', 'Oilseeds'), ('Roots and Tubers', 'Roots and Tubers'), ('Nuts', 'Nuts'), ('Animal', 'Animal'), ('Poetry', 'Poetry'), ('Tropical Crops', 'Tropical Crops'), ('Indistrial crops', 'Indusctrial Crop')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sell',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sell',
            name='harvest_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sell',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sell',
            name='origin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sell',
            name='packaging',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sell',
            name='shelf_life',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
