# Generated by Django 5.0.3 on 2024-04-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproduct', '0008_remove_sell_category_remove_sell_cost_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sell',
            old_name='article',
            new_name='caption',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='intro',
        ),
        migrations.AddField(
            model_name='sell',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
