# Generated by Django 5.0.2 on 2024-03-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='WhatsApp_No',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='category',
            field=models.CharField(choices=[('Staff', 'Staff'), ('Cooperative', 'Cooperative'), ('Farmer', 'Farmer'), ('Buyer', 'Buyer')], max_length=100, null=True),
        ),
    ]
